/**
 * NotesWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NotesWebApi);
  }
}(this, function(expect, NotesWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NotesWebApi.NoteApiApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NoteApiApi', function() {
    describe('deleteNote', function() {
      it('should call deleteNote successfully', function(done) {
        //uncomment below and update the code to test deleteNote
        //instance.deleteNote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNote', function() {
      it('should call getNote successfully', function(done) {
        //uncomment below and update the code to test getNote
        //instance.getNote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notesGet', function() {
      it('should call notesGet successfully', function(done) {
        //uncomment below and update the code to test notesGet
        //instance.notesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notesPost', function() {
      it('should call notesPost successfully', function(done) {
        //uncomment below and update the code to test notesPost
        //instance.notesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateNote', function() {
      it('should call updateNote successfully', function(done) {
        //uncomment below and update the code to test updateNote
        //instance.updateNote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
